config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get "about" , to:"about#about"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
 validates :title, presence: true, length:{ minimum: 6, maximum: 100}
 validates :description, presence: true , length:{minimum:15 , maximum: 200}
 
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def about
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
    def show
    end
    def index
      @articles = Article.all
    end
    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to @article
      else
        render 'new'
      end 
    end

    def edit

    end

    def update
      if @article.update(article_params)
        redirect_to @article
      else
         render 'edit' 
      end
    end

    def destroy
      @article.destroy
      redirect_to @article
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index

    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        @user = User.all
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/about/about.html.erb
About us

app/views/articles/edit.html.erb
<h1>i am editing </h1>

<%= form_with(model: @article,local: true ) do |f| %>
<p>
  <%= f.label :title %><br />
<%= f.text_field :title %>

</p>

<p>
  <%= f.label :description %><br />
<%= f.text_area :description %>

</p>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>showing all articles</h1>
<table>
<thead>
<tr>
<th> Title</th>
<th> Descriptions</th>
<th> Actions</th>

</tr></thead>

<tbody> 
<% @articles.each do |article|%>
    <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
        <td><%= link_to 'Show',article_path(article) %></td>
            <td><%= link_to 'Edit',edit_article_path(article)%></td>

    <td><%= link_to 'Delete', article_path(article), method: :delete %></td>

    </tr>
    <% end %>
</tbody>
</table>
    <p>
        <td><%= link_to 'Create new article',new_article_path %></td>
    </p>

app/views/articles/new.html.erb
<h1>i am new </h1>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>
<p>
  <%= f.label :title %><br />
<%= f.text_field :title %>

</p>

<p>
  <%= f.label :description %><br />
<%= f.text_area :description %>

</p>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1>I am showing articles</h1>
<p><strong>Title : </strong><%= @article.title %></p>
<p><strong>Description : </strong><%= @article.description %></p>

<%= link_to 'Edit',edit_article_path(@article) %>
<%= link_to 'Delete',article_path(@article), method: :delete %>
<%= link_to 'back',articles_path %>

app/views/home/index.html.erb
<h1>Home page </h1>  
<p>
<%= link_to 'Go to articles',articles_path %>
</p>
<p>
<%= link_to 'Go to about page',about_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <% flash.each do |name , msg| %>
     <%= msg %>
   <% end %>
   <%= yield %>
  </body>
</html>